# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jarvis(object):
    def setupUi(self, Jarvis):
        Jarvis.setObjectName("Jarvis")
        Jarvis.resize(443, 365)
        Jarvis.setMouseTracking(True)
        Jarvis.setLayoutDirection(QtCore.Qt.LeftToRight)
        Jarvis.setStyleSheet("background:transperent;\n"
"font: 87 10pt \"Segoe UI Black\";")
        self.centralwidget = QtWidgets.QWidget(Jarvis)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 441, 361))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/600430c1d22c731b94cf4e7dae6b398a.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(570, 20, 191, 51))
        self.textBrowser.setStyleSheet("background:transperent;\n"
"border: transperent;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(760, 20, 191, 51))
        self.textBrowser_2.setStyleSheet("background:transperent;\n"
"border:transperent;\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 230, 101, 23))
        self.pushButton_2.setStyleSheet("color: rgb(0, 171, 242);\n"
"font: 87 10pt \"Segoe UI Black\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 160, 75, 23))
        self.pushButton.setStyleSheet("font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(0, 162, 240);")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 421, 341))
        self.label_2.setStyleSheet("background:transperent")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/6226435516042edfe1a4514a44e2023a.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        Jarvis.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Jarvis)
        self.statusbar.setObjectName("statusbar")
        Jarvis.setStatusBar(self.statusbar)

        self.retranslateUi(Jarvis)
        QtCore.QMetaObject.connectSlotsByName(Jarvis)

    def retranslateUi(self, Jarvis):
        _translate = QtCore.QCoreApplication.translate
        Jarvis.setWindowTitle(_translate("Jarvis", "Jarvis"))
        self.pushButton_2.setText(_translate("Jarvis", "Terminate"))
        self.pushButton.setText(_translate("Jarvis", "start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jarvis = QtWidgets.QMainWindow()
    ui = Ui_Jarvis()
    ui.setupUi(Jarvis)
    Jarvis.show()
    sys.exit(app.exec_())
